// In-memory data store for local development when PostgreSQL is not running locally
// Automatically synchronized with PostgreSQL when DATABASE_URL is reachable

export const memoryStore = {
  users: [
    {
      id: 1,
      name: 'Rohan Mehta',
      email: 'rohan.mehta@roofproof.demo',
      password: 'password123',
      role: 'landlord',
      phone: '+91 98200 11223',
      city: 'Coorg, KA',
      occupation: null,
      organization: 'Mehta Luxury Estates',
      created_at: new Date().toISOString(),
    },
    {
      id: 2,
      name: 'Priya Nair',
      email: 'priya.nair@roofproof.demo',
      password: 'password123',
      role: 'landlord',
      phone: '+91 98450 33445',
      city: 'Jaipur, RJ',
      occupation: null,
      organization: 'Heritage Living India',
      created_at: new Date().toISOString(),
    },
    {
      id: 3,
      name: 'Arjun Sharma',
      email: 'arjun.sharma@roofproof.demo',
      password: 'password123',
      role: 'tenant',
      phone: '+91 98765 43210',
      city: 'Bangalore, KA',
      occupation: 'Senior Software Engineer',
      organization: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 4,
      name: 'Neha Kapoor',
      email: 'neha.kapoor@roofproof.demo',
      password: 'password123',
      role: 'tenant',
      phone: '+91 98111 22334',
      city: 'Mumbai, MH',
      occupation: 'Product Lead',
      organization: null,
      created_at: new Date().toISOString(),
    },
  ],

  properties: [
    {
      id: 1,
      landlord_id: 1,
      title: 'Misty Valley Villa',
      property_type: 'Luxury Villa',
      location: 'Coorg, Karnataka',
      monthly_rent: 65000,
      income_threshold: 195000,
      description: '3 BHK luxury villa with a private outdoor area, mountain views, furnished living spaces, and a modern kitchen.',
      image_url: '/houses/house1.jpg',
      landlord_name: 'Rohan Mehta',
      landlord_email: 'rohan.mehta@roofproof.demo',
      bedrooms: '3 BHK',
      bathrooms: '3 Bathrooms',
      furnishing: 'Fully Furnished',
      area_sqft: '2,400 sq.ft',
      parking: 'Covered (2 Cars + 2 Bikes)',
      deposit: '₹1,30,000 (2 Months)',
      preferred_tenants: 'Families & Working Professionals',
      available_from: 'Immediate Move-in',
      amenities: ['Mountain View', 'Private Balcony', 'Modular Kitchen', '24/7 Power Backup', 'Gated Community', 'High-Speed Fiber Ready'],
      total_applications: 0,
      created_at: new Date().toISOString(),
    },
    {
      id: 2,
      landlord_id: 1,
      title: 'Royal Courtyard Residence',
      property_type: 'Heritage House',
      location: 'Udaipur, Rajasthan',
      monthly_rent: 55000,
      income_threshold: 165000,
      description: 'Spacious heritage-style residence with a private courtyard, traditional interiors, large living areas, and a peaceful setting.',
      image_url: '/houses/house2.jpg',
      landlord_name: 'Rohan Mehta',
      landlord_email: 'rohan.mehta@roofproof.demo',
      bedrooms: '3 BHK',
      bathrooms: '3 Bathrooms',
      furnishing: 'Fully Furnished',
      area_sqft: '2,100 sq.ft',
      parking: 'Open Courtyard Parking (2 Cars)',
      deposit: '₹1,10,000 (2 Months)',
      preferred_tenants: 'Families & Expats',
      available_from: 'Immediate Move-in',
      amenities: ['Private Courtyard', 'Traditional Architecture', 'Modular Kitchen', '24/7 Security & CCTV', 'High-Speed Fiber Ready'],
      total_applications: 0,
      created_at: new Date().toISOString(),
    },
    {
      id: 3,
      landlord_id: 1,
      title: 'Heritage Garden Bungalow',
      property_type: 'Bungalow',
      location: 'Ooty, Tamil Nadu',
      monthly_rent: 48000,
      income_threshold: 144000,
      description: 'Charming 3 BHK bungalow with a large garden, traditional architecture, wooden interiors, spacious rooms, and a peaceful hill-station setting.',
      image_url: '/houses/house3.jpg',
      landlord_name: 'Rohan Mehta',
      landlord_email: 'rohan.mehta@roofproof.demo',
      bedrooms: '3 BHK',
      bathrooms: '2 Bathrooms',
      furnishing: 'Semi-Furnished',
      area_sqft: '1,950 sq.ft',
      parking: 'Dedicated Car Porch (1 Car)',
      deposit: '₹96,000 (2 Months)',
      preferred_tenants: 'Families & Remote Workers',
      available_from: 'Immediate Move-in',
      amenities: ['Private Botanical Garden', 'Fireplace', 'Hill Station Views', 'Power Backup', 'Pet Friendly'],
      total_applications: 0,
      created_at: new Date().toISOString(),
    },
    {
      id: 4,
      landlord_id: 1,
      title: 'Greenview Family Home',
      property_type: 'Family House',
      location: 'Bangalore, Karnataka',
      monthly_rent: 38000,
      income_threshold: 114000,
      description: 'Comfortable 3 BHK family home with generous natural light, multiple balconies, a quiet neighborhood, and nearby residential amenities.',
      image_url: '/houses/house4.jpg',
      landlord_name: 'Rohan Mehta',
      landlord_email: 'rohan.mehta@roofproof.demo',
      bedrooms: '3 BHK',
      bathrooms: '2 Bathrooms',
      furnishing: 'Semi-Furnished',
      area_sqft: '1,650 sq.ft',
      parking: 'Covered Parking (1 Car)',
      deposit: '₹76,000 (2 Months)',
      preferred_tenants: 'Families & Professionals',
      available_from: 'Immediate Move-in',
      amenities: ['Multiple Balconies', 'Park Facing', '24/7 Security', 'High-Speed Fiber Ready', 'Children Play Area'],
      total_applications: 0,
      created_at: new Date().toISOString(),
    },
    {
      id: 5,
      landlord_id: 2,
      title: 'Pink Palace Residence',
      property_type: 'Luxury Residence',
      location: 'Jaipur, Rajasthan',
      monthly_rent: 72000,
      income_threshold: 216000,
      description: 'Elegant 3 BHK residence inspired by Jaipur architecture, featuring ornate interiors, spacious common areas, and a distinctive heritage character.',
      image_url: '/houses/house5.jpg',
      landlord_name: 'Priya Nair',
      landlord_email: 'priya.nair@roofproof.demo',
      bedrooms: '3 BHK',
      bathrooms: '3 Bathrooms',
      furnishing: 'Fully Furnished',
      area_sqft: '2,600 sq.ft',
      parking: 'Covered Parking (2 Cars)',
      deposit: '₹1,44,000 (2 Months)',
      preferred_tenants: 'Families & Corporate Executives',
      available_from: 'Immediate Move-in',
      amenities: ['Rooftop Terrace', 'Jaipur Architecture', 'Modular Kitchen', 'Gym & Fitness', '24/7 Security & CCTV'],
      total_applications: 0,
      created_at: new Date().toISOString(),
    },
    {
      id: 6,
      landlord_id: 2,
      title: 'Glassfront Modern Estate',
      property_type: 'Modern Villa',
      location: 'Kolkata, West Bengal',
      monthly_rent: 52000,
      income_threshold: 156000,
      description: 'Characterful independent modern villa with glass facades, bright interiors, private entry, and a quiet residential setting.',
      image_url: '/houses/house6.jpg',
      landlord_name: 'Priya Nair',
      landlord_email: 'priya.nair@roofproof.demo',
      bedrooms: '3 BHK',
      bathrooms: '3 Bathrooms',
      furnishing: 'Fully Furnished',
      area_sqft: '2,300 sq.ft',
      parking: 'Covered Parking (1 Car + 2 Bikes)',
      deposit: '₹1,04,000 (2 Months)',
      preferred_tenants: 'Any Working Professionals',
      available_from: 'Immediate Move-in',
      amenities: ['Floor-to-Ceiling Glass', 'Private Garden', 'Modular Kitchen', '24/7 Power Backup', 'Smart Home Ready'],
      total_applications: 0,
      created_at: new Date().toISOString(),
    },
  ],

  applications: [],
};
